/** Roles JWT (`ROLE_*`) alineados con `SecurityConfig` del backend por prefijo de API. */

export const ROLE_ADMIN = 'ROLE_ADMINISTRADOR';
export const ROLE_MEDICO = 'ROLE_MEDICO';
export const ROLE_MEDICO_JEFE = 'ROLE_MEDICO-JEFE';
export const ROLE_RECEP = 'ROLE_RECEPCIONISTA';
export const ROLE_CAJERO = 'ROLE_CAJERO';
export const ROLE_FARMACIA = 'ROLE_FARMACIA';
export const ROLE_LAB = 'ROLE_LABORATORIO';
export const ROLE_RRHH = 'ROLE_RRHH';
export const ROLE_AUDITOR = 'ROLE_AUDITOR';

export const ROLES_PATIENTS = [ROLE_ADMIN, ROLE_MEDICO, ROLE_MEDICO_JEFE, ROLE_RECEP, ROLE_CAJERO];

/** POST/PUT/DELETE en `/api/patients/**` (backend; CAJERO solo GET). */
export const ROLES_PATIENTS_MUTATE = [ROLE_ADMIN, ROLE_MEDICO, ROLE_RECEP];

/** GET `/api/staff/**` y `/api/specialties/**` (pickers operativos; mutación solo RRHH). */
export const ROLES_STAFF_SPECIALTY_READ = [ROLE_ADMIN, ROLE_RRHH, ROLE_RECEP, ROLE_MEDICO, ROLE_MEDICO_JEFE];

export const ROLES_APPOINTMENTS = [ROLE_ADMIN, ROLE_MEDICO, ROLE_RECEP];
export const ROLES_ADMISSIONS_TRIAGE = [ROLE_ADMIN, ROLE_RECEP];
export const ROLES_MEDICAL_CARE = [ROLE_ADMIN, ROLE_MEDICO, ROLE_MEDICO_JEFE];
export const ROLES_MEDICAL_ORDERS = [ROLE_ADMIN, ROLE_MEDICO, ROLE_MEDICO_JEFE, ROLE_FARMACIA];
export const ROLES_LAB = [ROLE_ADMIN, ROLE_MEDICO, ROLE_MEDICO_JEFE, ROLE_LAB];
export const ROLES_IMAGING = [ROLE_ADMIN, ROLE_MEDICO, ROLE_MEDICO_JEFE];
export const ROLES_MEDICATIONS = [ROLE_ADMIN, ROLE_FARMACIA];
export const ROLES_PAYMENTS = [ROLE_ADMIN, ROLE_CAJERO];
export const ROLES_AUDIT = [ROLE_ADMIN, ROLE_AUDITOR];
export const ROLES_REPORTS = [ROLE_ADMIN, ROLE_AUDITOR];
export const ROLES_ADMIN_ONLY = [ROLE_ADMIN];
export const ROLES_RRHH_SPECIALTIES = [ROLE_ADMIN, ROLE_RRHH];
