export type DoctorReportType =
  | 'catalog'
  | 'appointments'
  | 'medical-cares'
  | 'medical-orders'
  | 'admissions'
  | 'productivity'
  | 'laboratory'
  | 'imaging'
  | 'triage';

export interface DoctorReportTypeOption {
  id: DoctorReportType;
  label: string;
  description: string;
  needsDateRange: boolean;
}

export const DOCTOR_REPORT_TYPES: DoctorReportTypeOption[] = [
  {
    id: 'catalog',
    label: 'Catálogo de médicos',
    description: 'Listado del personal médico con especialidad, colegiado, horario y asistencia.',
    needsDateRange: false,
  },
  {
    id: 'appointments',
    label: 'Citas por médico',
    description: 'Citas agendadas con motivo, confirmación por correo, fechas y estado.',
    needsDateRange: true,
  },
  {
    id: 'medical-cares',
    label: 'Atenciones médicas',
    description: 'Episodios clínicos con estado pendiente/completada, admisión, cita y hospitalización.',
    needsDateRange: true,
  },
  {
    id: 'medical-orders',
    label: 'Órdenes médicas',
    description: 'Órdenes emitidas por médico (laboratorio, imagen, farmacia, hospitalización).',
    needsDateRange: true,
  },
  {
    id: 'admissions',
    label: 'Admisiones por médico',
    description: 'Ingresos vinculados al médico de la atención o de la cita (consulta y emergencia).',
    needsDateRange: true,
  },
  {
    id: 'productivity',
    label: 'Productividad (resumen)',
    description: 'Conteos ampliados: citas, no asistió, atenciones pendientes, lab/img completados.',
    needsDateRange: true,
  },
  {
    id: 'laboratory',
    label: 'Laboratorio solicitado',
    description: 'Estudios con expediente, adjunto, muestra y tiempos de resultado.',
    needsDateRange: true,
  },
  {
    id: 'imaging',
    label: 'Imágenes solicitadas',
    description: 'Estudios radiológicos con informe y tiempos de realización.',
    needsDateRange: true,
  },
  {
    id: 'triage',
    label: 'Triage de emergencia',
    description: 'Clasificaciones de prioridad en admisiones EMERGENCIA por médico tratante.',
    needsDateRange: true,
  },
];

export interface DoctorCatalogReportRow {
  doctorId: number;
  doctorName: string;
  employeeCode: string;
  licenseNumber: string | null;
  specialtyName: string;
  schedule: string | null;
  attendance: string | null;
  active: boolean;
  hireDate: string | null;
}

export interface DoctorAppointmentReportRow {
  appointmentId: number;
  patientId: number;
  patientName: string;
  doctorId: number;
  doctorName: string;
  specialtyName: string;
  reason: string | null;
  notifyEmail: boolean;
  startAt: string;
  endAt: string;
  status: string;
}

export interface DoctorMedicalCareReportRow {
  medicalCareId: number;
  patientId: number;
  patientName: string;
  doctorId: number;
  doctorName: string;
  specialtyName: string;
  admissionId: number | null;
  appointmentId: number | null;
  admissionType: string | null;
  careStatus: string;
  autoGenerated: boolean;
  diagnosis: string;
  requiresHospitalization: boolean;
  careDate: string;
}

export interface DoctorMedicalOrderReportRow {
  medicalOrderId: number;
  medicalCareId: number;
  patientId: number;
  patientName: string;
  doctorId: number;
  doctorName: string;
  specialtyName: string;
  orderType: string;
  status: string;
  priority: string;
  orderDate: string;
}

export interface DoctorAdmissionReportRow {
  admissionId: number;
  patientId: number;
  patientName: string;
  doctorId: number | null;
  doctorName: string;
  specialtyName: string;
  appointmentId: number | null;
  medicalCareId: number | null;
  doctorSource: string;
  admissionType: string;
  status: string;
  admissionDate: string;
  dischargeDate: string | null;
}

export interface DoctorProductivityReportRow {
  doctorId: number;
  doctorName: string;
  specialtyName: string;
  appointmentCount: number;
  attendedAppointmentCount: number;
  noShowAppointmentCount: number;
  medicalCareCount: number;
  pendingCareCount: number;
  medicalOrderCount: number;
  admissionCount: number;
  labCompletedCount: number;
  labPendingCount: number;
  imagingCompletedCount: number;
}

export interface DoctorLaboratoryReportRow {
  laboratoryId: number;
  medicalOrderId: number;
  medicalCareId: number;
  patientId: number;
  patientName: string;
  doctorId: number;
  doctorName: string;
  recordNumber: string | null;
  status: string;
  sampleReceived: boolean;
  hasAttachment: boolean;
  orderDate: string;
  receptionAt: string | null;
  resultAt: string | null;
}

export interface DoctorImagingReportRow {
  imagingId: number;
  medicalOrderId: number;
  medicalCareId: number;
  patientId: number;
  patientName: string;
  doctorId: number;
  doctorName: string;
  studyType: string;
  status: string;
  hasReport: boolean;
  orderDate: string;
  scheduledAt: string | null;
  performedAt: string | null;
}

export interface DoctorTriageReportRow {
  triageId: number;
  admissionId: number;
  patientId: number;
  patientName: string;
  doctorId: number | null;
  doctorName: string;
  specialtyName: string;
  admissionType: string;
  priority: string;
  targetMinutes: number | null;
  registeredAt: string;
}

export type DoctorReportRow =
  | DoctorCatalogReportRow
  | DoctorAppointmentReportRow
  | DoctorMedicalCareReportRow
  | DoctorMedicalOrderReportRow
  | DoctorAdmissionReportRow
  | DoctorProductivityReportRow
  | DoctorLaboratoryReportRow
  | DoctorImagingReportRow
  | DoctorTriageReportRow;

export const DOCTOR_APPOINTMENT_STATUSES = [
  'PROGRAMADA',
  'REPROGRAMADA',
  'CANCELADA',
  'ATENDIDA',
  'NO_ASISTIO',
] as const;

export const DOCTOR_ADMISSION_STATUSES = [
  'PENDIENTE',
  'ADMITIDO',
  'ALTA',
  'TRANSFERIDO',
  'RECHAZADO',
  'ANULADO',
] as const;

export const DOCTOR_ADMISSION_TYPES = ['CONSULTA', 'EMERGENCIA', 'HOSPITALIZACION'] as const;

export const DOCTOR_ORDER_TYPES = ['LABORATORIO', 'IMAGEN', 'FARMACIA', 'HOSPITALIZACION'] as const;

export const DOCTOR_ORDER_STATUSES = [
  'PENDIENTE',
  'EN_PROCESO',
  'COMPLETADO',
  'RECHAZADO',
  'PARCIAL',
  'ANULADO',
] as const;

export const DOCTOR_LAB_IMAGING_STATUSES = ['PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'RECHAZADO', 'ANULADO'] as const;

export const DOCTOR_TRIAGE_PRIORITIES = ['I', 'II', 'III', 'IV'] as const;

export const DOCTOR_ATTENDANCE_TYPES = ['PRESENTE', 'AUSENTE', 'PERMISO', 'VACACIONES'] as const;

export const DOCTOR_CARE_STATUSES = ['PENDIENTE', 'COMPLETADA'] as const;
